### ISSUE TITLE
Receiving Timeouts from Chaos-monkey for my Application

### ISSUE THREAD

**Issue by akshaypatel2397** [codecentric/chaos-monkey-spring-boot#10]
I don't think this is a real issue. But, maybe I don't have a full understanding of how it works or what should have happened if I run my SpringBoot with ChaosMonkey. I have read the documentation but cannot fully understand how do I prove it is working or not. Can you please give us or explain to us what really happens when our Controllers, Service, Repository classes are intercepted and how was the problem found. 

For me when I run my application and the demo app attached to this project I - I receive Chaos Monkey -timeout. Don't know what that is? Can you please help me, figure out.

**Comment by MrBW** [comment]
With the Chaos Monkey for Spring Boot you are able to simulate an infected App and all consuming Apps must be able to handle timeouts, failures and exceptions. Chaos Monkey shows you the bugs in your architecture and helps you to build your app resilient.

For example:
You build an App which is consuming my chaos-monkey-demo app. Your App must be able to handle long running calls, for example you could implement a fallback. You can achieve this by using Hystrix or resilience4j, for example.

https://github.com/Netflix/Hystrix
https://github.com/resilience4j/resilience4j

I have done a lot of talks on the topic resilience and created a running demo to show a lot of resilience pattern you could you to make your consuming app stable.

Demo Hystrix, Spring Cloud, Spring Cloud Netflix:
https://github.com/MrBW/resilient-transport-service

Slides (german only, sorry!):
https://speakerdeck.com/mrbw/spring-cloud-netf

Chaos Monkey is active if you see the Chaos Monkey logo in your app in wich he is running and of course if you see any exceptions or log entries in your attack Spring Boot App.

If you have any question don´t hesitate to contact me!

**Comment by MrBW** [comment]
I´m closing this issue, if you need more informations just ping me!

**Comment by akshaypatel2397** [comment]
Thank you MrBW.
