### ISSUE TITLE
BeanCurrentlyInCreationException after upgrade to 2.1.0

### ISSUE THREAD

**Issue by smcgregor83** [codecentric/chaos-monkey-spring-boot#118]
After upgrading from 2.0.2 to 2.1.0 our Spring Boot applications will no longer start due to a BeanCurrentlyInCreationException.

## Expected Behavior
Spring Boot application should start.

## Current Behavior
Spring Boot application does not start.

## Possible Solution
Not sure. This only occurs when spring-cloud-starter-sleuth is also on the classpath.

## Steps to Reproduce
[demo.zip](https://github.com/codecentric/chaos-monkey-spring-boot/files/3589861/demo.zip)

## Context (Environment)
Automated upgrade of 3rd party library versions.

**Comment by WtfJoke** [comment]
Hi Gregor

Thanks for your report. 👍 
I was able to reproduce it as well, using your demo.zip. The error doesnt occur with version 2.0.2. 
I am going to ask around in our team if somebody can have a look at it.

**Comment by srempfer** [comment]
Narrowed down the problem to this library
```
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-context</artifactId>
        </dependency>
```
and the Auto-Configuration
```
org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration.class
```

**Comment by maiksensi** [comment]
We'll prepare a release in the next days.

**Comment by WtfJoke** [comment]
Some analysis notes:

Tested by adding this dependency:
```
<dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-context</artifactId>
            <version>2.1.3.RELEASE</version>
</dependency>
```

Issue was caused by  `org.springframework.cloud.context.properties.ConfigurationPropertiesBeans` and SpringComponentAspect (ChaosMonkeyComponentWatcher). 

In 2.0.2 watchers werent configurable at runtime and fixed with #84 (which kinda "reintroduced" this bug, but problem already existed earlier)

For more details see #120

**Comment by WtfJoke** [comment]
Latest 2.2.0-SNAPSHOT should solve the issue, see https://codecentric.github.io/chaos-monkey-spring-boot/#snapshots

**Comment by WtfJoke** [comment]
[2.2.1 released](https://github.com/codecentric/chaos-monkey-spring-boot/releases/tag/2.1.1) containing this bugfix

**Comment by smcgregor83** [comment]
Thanks very much for investigating and fixing this. I have tested 2.2.1 and my applications start correctly again.
