### ISSUE TITLE
changes.adoc styling should be clear

### ISSUE THREAD

**Issue by WtfJoke** [codecentric/chaos-monkey-spring-boot#132]
If [changes.adoc](https://github.com/codecentric/chaos-monkey-spring-boot/blob/master/chaos-monkey-docs/src/main/asciidoc/changes.adoc) is empty at beginning of a release, its not obvious what style the file should maintain.

PR with wrong styling will be created and needs review changes, see #127, #130 , #131

Asciidoc-comments should be made about how the styling should be, by giving examples.
Examples should be given for all sections (Bug Fixes, Improvements, New Features, Contributors)

For example in Section Improvements:
`// - https://github.com/codecentric/chaos-monkey-spring-boot/pull/XXX[#XXX] My Pull-Request`

An example how a properly formatted changes.adoc should look like can be found [here](https://raw.githubusercontent.com/codecentric/chaos-monkey-spring-boot/2.1.0/chaos-monkey-docs/src/main/asciidoc/changes.adoc).

**Comment by maiksensi** [comment]
In pytest we're using `towncrier` to automatically generate a changelog and the entries. Maybe there is a good workfow we can adapt (or a tool for java) to do similar things with `changes.adoc`?

**Comment by WtfJoke** [comment]
[Maven changes plugin](http://maven.apache.org/plugins/maven-changes-plugin/)  seems to be a possible solution. First look (without using it), doesnt look that great (having changes in xml...), export to github is possible, though

**Comment by olfarmer** [comment]
I'll work on this.
