### ISSUE TITLE
Add support for triggering attacks through a management api while app is running?

### ISSUE THREAD

**Issue by russmiles** [codecentric/chaos-monkey-spring-boot#14]
I would love to be able to trigger and turn-off attacks at runtime as this would then allow me to run temporary experiments against the system without restarting applications to load new configuration parameters around chaos.

I was thinking of something along the lines of a runtime switch to enable the management API:

```
chaos.monkey.api.enabled
```

There will likely be limitations about what can be triggered, depending on what has been enabled.

**Comment by MrBW** [comment]
It´s already there, prepared for our next release ;-) 

There are some endpoints coming to enable/disable the Chaos Monkey, change the behave of all Assaults and so on. 

Take a look at:
https://github.com/codecentric/chaos-monkey-spring-boot/blob/master/chaos-monkey-spring-boot/src/main/java/de/codecentric/spring/boot/chaos/monkey/endpoints/ChaosMonkeyController.java

What do you think?

**Comment by MrBW** [comment]
Hi,

implementation for Spring 2.0.1 is done...
I´ve created a first SNAPSHOT version for you, please take a look at:
https://oss.sonatype.org/content/repositories/snapshots/

`<dependency>
  <groupId>de.codecentric</groupId>
  <artifactId>chaos-monkey-spring-boot</artifactId>
  <version>2.0.0-SNAPSHOT</version>
</dependency>`

I also created a new documentation, you can find the docs here:
https://codecentric.github.io/chaos-monkey-spring-boot/2.0.0-SNAPSHOT/

Currently I´m preparing a Spring Boot 1.5 release of the Chaos Monkey for Spring Boot. It will also contain a Spring Boot Actuator endpoint to configure at runtime. But please check out my last changes on Spring Boot 2.0.1.

Bye
Benjamin

**Comment by msrraju13** [comment]
Hi,

I am looking for Spring Boot 1.5 release of the Chaos Monkey, please let me know when it's available.

Thank You.
