### ISSUE TITLE
Migrate ChaosMonkeyRequestScopeTest to JUnit5

### ISSUE THREAD

**Issue by WtfJoke** [codecentric/chaos-monkey-spring-boot#145]
In #141 tests were migrated to JUnit 5. 

But `ChaosMonkeyRequestScopeTest` wasnt migrated, because of [UnnecessaryStubbingException](https://static.javadoc.io/org.mockito/mockito-core/2.6.5/org/mockito/exceptions/misusing/UnnecessaryStubbingException.html) caused by test method `isChaosMonkeyExecutionDisabled`.

**Comment by WtfJoke** [comment]
Not sure how to fix it, the unnecessary stubs are only for the disabled case. 
Extract them into separate class could be a solution.

**Comment by Riggs333** [comment]
One way how to solve this might be the use of JUnit's `@Nested` classes feature:
https://junit.org/junit5/docs/current/user-guide/#writing-tests-nested
See PR #146 as a suggestion for discussion.

There surely are other ways and different tastes, of course. ;-)

I'm interested in what you're all thinking about this.

**Comment by WtfJoke** [comment]
The `@Nested` looks like an elegant solution for this. At least I think its better than splitting the tests (and have only one test method in a second class file).

If nobody comes up with a better idea, I would suggest merging #146
