### ISSUE TITLE
Docs syntax is faulty

### ISSUE THREAD

**Issue by maiksensi** [codecentric/chaos-monkey-spring-boot#150]
## Current Behavior
Seems we have a little syntax error in our markdown file. 
<img width="1428" alt="image" src="https://user-images.githubusercontent.com/6359386/69094092-08d41680-0a50-11ea-8fe2-c2400155069f.png">

## Expected Behavior
One should be able to copy paste the maven dependency. 

## Possible Solution
We should fix the part starting with ```xml which seems to me is ment to outline that there is xml following.

**Comment by WtfJoke** [comment]
Fixed by #153
