### ISSUE TITLE
Unnecessary Empty-Check on watchedCustomService

### ISSUE THREAD

**Issue by WtfJoke** [codecentric/chaos-monkey-spring-boot#151]
## Expected Behavior

Dont check Property-List (`watchedCustomServices`) twice for empty.

## Current Behavior

In `de.codecentric.spring.boot.chaos.monkey.component.ChaosMonkeyRequestScope#callChaosMonkey` the `watchedCustomServices` is checked twice for empty. 

First in AssaultProperties-Method:
https://github.com/codecentric/chaos-monkey-spring-boot/blob/d6782dca9e206e4dc6ad045ab061885fdc284e3d/chaos-monkey-spring-boot/src/main/java/de/codecentric/spring/boot/chaos/monkey/configuration/AssaultProperties.java#L118-L121

then again in the callChaosMonkey-Method:
https://github.com/codecentric/chaos-monkey-spring-boot/blob/d6782dca9e206e4dc6ad045ab061885fdc284e3d/chaos-monkey-spring-boot/src/main/java/de/codecentric/spring/boot/chaos/monkey/component/ChaosMonkeyRequestScope.java#L90

**Comment by Caps-Looking** [comment]
I'd like to work with that.
