### ISSUE TITLE
Drop 1.5.x support

### ISSUE THREAD

**Issue by maiksensi** [codecentric/chaos-monkey-spring-boot#159]
I would like  to drop Spring Boot support for 1.5.x. It is EOL https://spring.io/blog/2018/07/30/spring-boot-1-x-eol-aug-1st-2019 
I would also add some notes in the docs, that we adhere to the spring boot lifecycle in order to be transparent about dropping support for versions.

**Comment by WtfJoke** [comment]
I think we can close this issue. 

We dropped the version compatibility matrix and instead publish the spring boot version which was used to build the cmsb release in the release notes. 

Additionally no issues for such an old version was requested.
