### ISSUE TITLE
Spring boot version 1.5.2.RELEASE is supported by chaos-monkey-spring-boot 1.0.1?

### ISSUE THREAD

**Issue by msrraju13** [codecentric/chaos-monkey-spring-boot#16]
Hi Team,

is spring boot version 1.5.2.RELEASE is supported by chaos-monkey-spring-boot 1.0.1, we are seeing below error when trying to run the app by activating chaos monkey.

`org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'de.codecentric.spring.boot.chaos.monkey.configuration.EndpointConfiguration': Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [de.codecentric.spring.boot.chaos.monkey.configuration.EndpointConfiguration$$EnhancerBySpringCGLIB$$bd1c4f5a]: No default constructor found; nested exception is java.lang.NoSuchMethodException: de.codecentric.spring.boot.chaos.monkey.configuration.EndpointConfiguration$$EnhancerBySpringCGLIB$$bd1c4f5a.<init>()`

**Comment by MrBW** [comment]
Hi,

implementation for Spring 1.5.x is done...
I´ve created a first SNAPSHOT version for you, please take a look at:
https://oss.sonatype.org/content/repositories/snapshots/

<dependency>
  <groupId>de.codecentric</groupId>
  <artifactId>chaos-monkey-spring-boot</artifactId>
  <version>1.5.0-SNAPSHOT</version>
</dependency>

Documentation can be found here: 
https://codecentric.github.io/chaos-monkey-spring-boot/1.5.0-SNAPSHOT/

Bye,
Benjamin

**Comment by MrBW** [comment]
Duplicated issue #5
