### ISSUE TITLE
Consolidate integration test naming

### ISSUE THREAD

**Issue by fletchgqc** [codecentric/chaos-monkey-spring-boot#165]
We currently have

- MemoryAssaultIntegrationTest
- ChaosMonkeyRequestScopeRestEndpointDisabledIntTest
- ChaosMonkeyRequestScopeRestEndpointIntTest
- DefaultSettingsIntegrationTest
- ChaosDemoApplicationDefaultProfileTest
- ChaosDemoApplicationChaosMonkeyRequestScopeProfileTest

My questions:

1. Can we unify the naming?
  - I would suggest IntegrationTest. No need to use the "ChaosDemoApplication" prefix.
  - Actually, if you are willing to be more adventurous, I'd suggest removing "Test" from all the test class names. Under JUnit5 you don't need that anymore. So the integration tests would just end with "Integration".
2. Should integration tests all be in the same directory, or split up around where they belong? I tend towards having them where they contextually belong.
3. What are the request scope profile tests about? What is a ChaosMonkeyRequestScope? I'm wondering whether the test ChaosDemoApplicationDefaultProfileTest is actually useful.

**Comment by maiksensi** [comment]
👍 from me on all of your points. Maybe @MrBW can answer your last question. I haven't had a in depth look at it so far.
