### ISSUE TITLE
Build not broken by lines which are too long

### ISSUE THREAD

**Issue by fletchgqc** [codecentric/chaos-monkey-spring-boot#169]
I noticed that checkstyle line length validation is suppressed. Why?

By the way, I used this successfully on a previous project: https://github.com/coveooss/fmt-maven-plugin. It's just a helper which reformats the code on build. A colleague managed to use it to break the build on the build server when the format wasn't right (i.e., when formatting the code changed anything). Let's see how we go with Checkstyle for now, just FYI in case we have issues with that.

**Comment by maiksensi** [comment]
Line length in particular is a tricky rule. In our case I decided to disable it, as I would say that line length doesn't help your code quality in general. Depending on the change the reviewer has to decide whether it makes sense to use a different approach (and this line length won't be an issue) or whether it is okay to have a long line (for example a long string with an error message which is more readable (imho) when in one line. But let's keep that open for now. The plugin looks interesting. 
I am missing something like prettier or black for java, that would help alot as it only tackles formatting, not semantic rules.

**Comment by fletchgqc** [comment]
OK.

BTW, personally I prefer line length set to 120-140, I find 100 encourages poor variable names. But that's just life with the Google Java Formatter, intentionally unconfigurable.
