### ISSUE TITLE
Checkstyle reports violations on code formatted by Intellij Google Style Plugin

### ISSUE THREAD

**Issue by fletchgqc** [codecentric/chaos-monkey-spring-boot#170]
After installing the Intellij plugin and code style as described on the Contribution Guide, format code with IntelliJ.

When running mvn:verify, I would expect it to pass.

Instead, checkstyle complains about a few violations regarding line indentation and brackets on next line.

Tonight I manually formatted code to pass checkstyle. Eugh.

Here is the commit where I manually formatted the code:
https://github.com/fletchgqc/chaos-monkey-spring-boot/commit/4112fc2a743646baccfa223c9df0a3c93defb861

To reproduce, clone my project, check out the rest-client-assault branch and try auto-formatting e.g. the file WebClientAssaultTest. Then run mvn:verify, and checkstyle will fail the build.

My suggestion: I used this successfully on a previous project: https://github.com/coveooss/fmt-maven-plugin. It's just a helper which reformats the code on build. The nice thing is that instead of telling you that your code is broken, it just automatically reformats it.

For the build server, a colleague managed to use it to break the build when the format wasn't right (i.e., when formatting the code changed anything). I can ask him how he did it or maybe we can just figure it out. What do you think?

We should address this with priority, because the current status is really painful and puts a big tax on any work on the project.

**Comment by maiksensi** [comment]
I can't see why we should do that. Just got for it and see how it works out.

**Comment by maiksensi** [comment]
I actually can't believe formatting java code is such a pain. Isn't there a better solution like black or prettier?

**Comment by maiksensi** [comment]
Please wait before going a head with this and let's check out spotless first (https://github.com/diffplug/spotless) it looks promising. 

@fletchgqc did you integrate the checkstyle into intellij? By adding the google formatter plugin and stuff? I think I outlined the process in the docs: https://github.com/codecentric/chaos-monkey-spring-boot/blob/master/CONTRIBUTING.adoc#intellij-setup

**Comment by maiksensi** [comment]
I created a fast implementation with spotless and it works much better compared to checkstyle: check out out and let me know whether I should submit a pr https://github.com/maiksensi/chaos-monkey-spring-boot/tree/feature/setup-proper-style-formatter

**Comment by WtfJoke** [comment]
As already said spotless looks quite neat, see my comment in the previous bug https://github.com/codecentric/chaos-monkey-spring-boot/issues/133#issuecomment-556076606. So if your experience its much better with spotless, lets go to spotless 💪

**Comment by maiksensi** [comment]
I'll submit a pr in the next days.

**Comment by maiksensi** [comment]
related PR which introduces spotless ❤️ : #175
