### ISSUE TITLE
why killApplicationActive property is not killing application 

### ISSUE THREAD

**Issue by 4n0nym1ty** [codecentric/chaos-monkey-spring-boot#171]
chaos:
  monkey:
    enabled: true
    assaults:
      level: 3
      latencyRangeStart: 1000
      latencyRangeEnd: 4500
      latencyActive: false
      exceptionsActive: false
      killApplicationActive: true

i m trying kill microservice but still application is running,  why its happen i don't know , did i make any mistake in configuration.

**Comment by fletchgqc** [comment]
Hi @LifeOfBinaries , I believe that you need to schedule KillApplication and Memory assaults via cron expressions, they are not triggered by HTTP requests. Search the doco for "cron" and see if that helps.

**Comment by 4n0nym1ty** [comment]
Hi @fletchgqc, i apply cron expn to kill app in aws env.

**Comment by devenparab** [comment]
> Hi @fletchgqc, i apply cron expn to kill app in aws env.

hi 4n0nym1ty can you please share how have you configured the cron? That will be mighty helpful.
