### ISSUE TITLE
ChaosMonkeyConfiguration class issue while injecting Parameter 0 of method scheduler with consul Spring Boot

### ISSUE THREAD

**Issue by smreddy2004** [codecentric/chaos-monkey-spring-boot#184]
I have a Spring Boot Hoxton.SR6 application and when I start to use both chaos-money and consul-discovery

		<dependency>
			<groupId>de.codecentric</groupId>
			<artifactId>chaos-monkey-spring-boot</artifactId>
			<version>2.2.0</version>
		</dependency>

		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-consul-discovery</artifactId>
		</dependency>

## Expected Behavior
It should ideally pick the scheduler even if more than one such instance exists. 

## Current Behavior
It fails with and exception 
Description:

Parameter 0 of method scheduler in de.codecentric.spring.boot.chaos.monkey.configuration.ChaosMonkeyConfiguration required a single bean, but 2 were found:
	- taskScheduler: defined by method 'taskScheduler' in class path resource [org/springframework/boot/autoconfigure/task/TaskSchedulingAutoConfiguration.class]
	- catalogWatchTaskScheduler: defined by method 'catalogWatchTaskScheduler' in class path resource [org/springframework/cloud/consul/discovery/ConsulCatalogWatchAutoConfiguration.class]

## Possible Solution
It is unable to choose between the 2 schedulers available. Looking at the scheduler method of ChaosMonkeyConfiguration, may be it can be solved by using Qualifier to inject specific scheduler like "taskScheduler"

## Steps to Reproduce

[SampleProjectToReproduceError.zip](https://github.com/codecentric/chaos-monkey-spring-boot/files/5014604/SampleProjectToReproduceError.zip)

Import the zip as Maven project and start running as Spring Boot application.

**Comment by maiksensi** [comment]
Hey @smreddy2004, 

I didn't have the time to look at the problem in detail, but if you have an idea on how to fix it, feel free to open a MR and we can discuss details there. Do you think your proposed fix will have side effects?

**Comment by smreddy2004** [comment]
Hi @maiksensi ,

I don't think the fix will have any side effects. Today by default it autowires 'taskScheduler' bean since it is the only TaskScheduler bean available. But with consul in the classpath now there is conflict because of another TaskScheduler bean available named 'catalogWatchTaskScheduler'.

I am new to contributing code on github, so I believe when you say "open an MR", you are referring to "Open a pull request" and make code changes. Please let me know if I got it wrong.

**Comment by maiksensi** [comment]
>  am new to contributing code on github, so I believe when you say "open an MR", you are referring to "Open a pull request" and make code changes. Please let me know if I got it wrong.

This is absolutely what I ment. Sorry that I didn't made myself more clear. Currently, we don't have much time to help move this project forward, so your contribution is highly appreciated. Let me know if I can help you with anything with the changes.  
Our contribution guide should help you setup the project: https://github.com/codecentric/chaos-monkey-spring-boot/blob/07b111deca6e195b03e56f0d82254e08f03f4b59/CONTRIBUTING.adoc

**Comment by smreddy2004** [comment]
@maiksensi  Sure. I will work on it.
