### ISSUE TITLE
Unable to register Bean exception, when setting the watcher - repository to true

### ISSUE THREAD

**Issue by SravanMaddipati** [codecentric/chaos-monkey-spring-boot#185]
Hi,

Currently am using Springboot 2.1.5 version and chaos monkey version of 2.0.2 along with swagger 2.9.2

When i start the application, making the watcher - repository set to true, am getting the below exception from springfox and application is  not getting started up.

PFB the log:

The bean 'org.springframework.context.annotation.internalScheduledAnnotationProcessor', defined in class path resource [org/springframework/scheduling/annotation/SchedulingConfiguration.class], could not be registered. A bean with that name has already been defined in null and overriding is disabled.\r\n\r\nAction:\r\n\r\nConsider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true\r\n

Any leads will be helpful here.

Thanks in advance...

**Comment by maiksensi** [comment]
Hey @SravanMaddipati, 
that sounds alot like  this is interfering with our addition of  a swagger api by @fletchgqc. Maybe he knows what todo. To me it looks like we either remove our swagger ui in such a case (that is probably what the bean definition overriding = true will do) or we remove it completely. Any other suggestions?

**Comment by SravanMaddipati** [comment]
Hi @maiksensi ,

I got your point, that by removing swagger ui we can eliminate the issue..but the thing is i need both to be in place and hence looking for an alternative solution.

**Comment by SravanMaddipati** [comment]
If i remove the swagger configuration am getting the error of same type this time with micrometer dependency related to metrics.

PFB logs for the same:

Error creating bean with name 'meterRegistryPostProcessor' defined in class path resource [org/springframework/boot/actuate/autoconfigure/metrics/MetricsAutoConfiguration.class]: BeanPostProcessor before instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.cache.annotation.ProxyCachingConfiguration': Initialization of bean failed; nested exception is java.lang.IllegalArgumentException: warning no match for this type name: org.springframework.data.repository.CrudRepository

**Comment by maiksensi** [comment]
Hmm, this looks like a different problem. As it is about the ProxyCachingConfiguration not able to handle CrudRepository. I am not sure this is related. If you can give us a minimal reproducible example (preferably a git repo which we can check out) we can have a look at it. Maybe it makes sense to open a another issue?
