### ISSUE TITLE
Enhancement to automatically ignore Final classes in watcher Aspect classes

### ISSUE THREAD

**Issue by abhishekans21** [codecentric/chaos-monkey-spring-boot#188]
Hi,
Currently I am using spring boot version 2.1.6 and chaos monkey version 2.1.1

I have a final class with @Component annotation, unfortunately it is imported from a third party library and thus cannot be made "non-final".

**The issue I am facing is as follows:**
When I start my application the **SpringComponentAspect** tries to do a pointcut on all the classes in my application that have a @Component annotation, but since one of my component classes is final, it results in an exception.
"Could not generate CGLIB subclass of class com.test.abc: Common causes of this problem include using a final class or a non-visible class; nested exception is java.lang.IllegalArgumentException: Cannot subclass final class com.test.abc"

I understand that this exception is not from chaos monkey but thrown from Spring AOP. However, this puts me in a deadlock as I can't change the third party code that I've imported.

I was wondering if the Aspect classes in de.codecentric.spring.boot.chaos.monkey.watcher package be refactored so as to ignore final classes?

**Resolution**:  @Pointcut(within(@org.springframework.stereotype.Component *) && !within(is(FinalType))

Also the same can be applied for other pointcuts as well e.g: controller aspect, service aspect, etc.

Any help on this is appreciated.

**Comment by WtfJoke** [comment]
Hi @abhishekans21 

Thanks for your bug report. Yeah I think it would make sense to exclude final classes in the Aspect classes.

Until this is fixed, you can try to configure different watchers (instead of component). 
Or if you need to attack `@Component` you can customize the watchers to only include the components you want using the property `watchedCustomServices` see https://codecentric.github.io/chaos-monkey-spring-boot/2.2.0/#_customize_watcher

**Comment by abhishekans21** [comment]
Hi @WtfJoke 

watchedCustomServices is helpful when I want to set assaults on a specific @Component, but this bug won't allow the application to boot up successfully. In my case, I followed a workaround by overriding the Bean definition for **componentAspect** , this helped me in deploying my application, without having to worry about Spring AOP complaining about final classes.

On the contrary, the workaround shouldn't be the final solution, thus, I've raised a PR to address it.
You can test/review it and let me know if any clarifications are needed.

**Comment by fletchgqc** [comment]
Closed by https://github.com/codecentric/chaos-monkey-spring-boot/pull/191. Great first PR @sappo. Thanks for the report and showing us the solution @abhishekans21 - the other PR is a more complete so we'll go with that one.
