### ISSUE TITLE
Custom annotation on Spring bean not found

### ISSUE THREAD

**Issue by LogicBig** [codecentric/chaos-monkey-spring-boot#189]
When we enabled Chaos-monkey during bootstrap time,  custom annotation @MyAnnoation not found on spring beans annotated with @Service (which is also annotated with @MyAnnoation)

` @Service
 @MyAnnoation
 public class MyService{

 }`

... more such services

@Component
public class AnotherBean{

 @Autowired
 private List&lt;MyService> services;

@PostConstruct
private void init(){
   for (service s: services){
   MyAnnoation[] ma = s.getClass().getDeclaredAnnoationByType(MyAnnoation.class); //returns empty array   
}
 }
}

Note that MyAnnoation is defined with RetentionPolicy.Runtime and is also annotated with Java 8 Repeatable.

Since choas-monkey uses AOP, is it ignoring custom annoations?

**Comment by pgxyz** [comment]
This works in version 2.0.2 but fails in version 2.2.0

**Comment by LogicBig** [comment]
Any plans to fix this issue?

**Comment by checketts** [comment]
Can you create a simple project the reproduces this? That will help us look into it
