### ISSUE TITLE
ChaosMonkey assaulted before application started

### ISSUE THREAD

**Issue by chainho** [codecentric/chaos-monkey-spring-boot#193]
The chaosMonkey assault will fired when Spring boot application starting. So if there is a bean contains a `@PostConstruct` and this method will invoke another Service/Bean method, now  RuntimeExcetpion will generate, and the start flow will block.  

Does chaosMonkey  have a configuration, support fired later,       when the application started finished 

Thanks in advance.

**Comment by WtfJoke** [comment]
Hi @chainho 
You could disable the chaos monkey and enable it by the actuator endpoint after your application is fully started.

Check out the docs about [the actuator endpoint](https://codecentric.github.io/chaos-monkey-spring-boot/2.2.0/#endpoints)

**Comment by WtfJoke** [comment]
I'll close this, feel free to comment if you still need help
