### ISSUE TITLE
Config errors 

### ISSUE THREAD

**Issue by ranajit-jana** [codecentric/chaos-monkey-spring-boot#20]
With spring boot 1.4 i am getting the config errors. Upgraded the  project to 1.5  but the  config error does not go away . If i remove the chaos monkey jar from pom.xml file then runtime error goes away.

<code>
org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [com.wipro.coe.microservices.web.config.WebConfig]; nested exception is java.lang.IllegalStateException: Could not evaluate condition on org.springframework.boot.actuate.autoconfigure.web.server.ManagementContextAutoConfiguration$DifferentManagementContextConfiguration due to org/springframework/boot/web/reactive/context/ConfigurableReactiveWebApplicationContext not found. Make sure your own configuration does not rely on that class. This can also happen if you are @ComponentScanning a springframework package (e.g. if you put a @ComponentScan in the default package by mistake)</code>

**Comment by MrBW** [comment]
Hi,

implementation for Spring 1.5.x is done...
I´ve created a first SNAPSHOT version for you, please take a look at:
https://oss.sonatype.org/content/repositories/snapshots/

<dependency>
  <groupId>de.codecentric</groupId>
  <artifactId>chaos-monkey-spring-boot</artifactId>
  <version>1.5.0-SNAPSHOT</version>
</dependency>

Documentation can be found here: 
https://codecentric.github.io/chaos-monkey-spring-boot/1.5.0-SNAPSHOT/

Spring 1.4 is not supported, sorry!

Bye,
Benjamin

**Comment by MrBW** [comment]
Please see: https://github.com/codecentric/chaos-monkey-spring-boot/issues/5
