### ISSUE TITLE
Application fails to start up on adding chaos monkey

### ISSUE THREAD

**Issue by muskans71** [codecentric/chaos-monkey-spring-boot#206]
My spring boot application works fine but when I add spring.profiles.active=chaos-monkey in application properties, it fails to start up. `org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'chaosMonkeyRequestScope' defined in class path resource [de/codecentric/spring/boot/chaos/monkey/configuration/ChaosMonkeyConfiguration.class]: BeanPostProcessor before instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'metaDataSourceAdvisor': Cannot resolve reference to bean 'methodSecurityMetadataSource' while setting constructor argument; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.security.config.annotation.method.configuration.GlobalMethodSecurityConfiguration': Initialization of bean failed; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'org.springframework.context.annotation.ConfigurationClassPostProcessor.importRegistry' available
`

**Comment by WtfJoke** [comment]
Hi @muskans71 
Can you please provide a minimal working example repo, which demonstrates this error? Then we can have a look at it.
