### ISSUE TITLE
Question: how to inject this into k8s pod

### ISSUE THREAD

**Issue by niebomin** [codecentric/chaos-monkey-spring-boot#207]
My system is deployed in k8s cluster.  Is there a way dynamically inject those chaoses into containers?

**Comment by WtfJoke** [comment]
Hi @niebomin 

I personally havent used chaos monkey in a k8s cluster yet, but I think @fletchgqc did (maybe he can tell you more).

However it should work the same way like in a non kubernetes way. 
You can use actuator to enable chaos monkey.

A more k8 way of doing this, if you have a k8s deployment, you simply could set the spring profile via environment-variables. Then your containers get updated and chaos monkey gets active :)
