### ISSUE TITLE
Application fails to start once having BeanPostProcessor implementation

### ISSUE THREAD

**Issue by Bknisan** [codecentric/chaos-monkey-spring-boot#208]
application  fails to start once BeanPostProcessor interface implemented due to circular dependency. 

error log:

Caused by: org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'chaosMonkeyRequestScope': Requested bean is currently in creation: Is there an unresolvable circular reference?
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.beforeSingletonCreation(DefaultSingletonBeanRegistry.java:355) ~[spring-beans-5.3.5.jar:5.3.5]

**Comment by WtfJoke** [comment]
Hi @Bknisan would be great if you can provide a minimal example project so we can reproduce this and eventually fix this

**Comment by Bknisan** [comment]
Hi @WtfJoke, the project is not the point here. it is reproducible in any spring boot project with any compatible chaos monkey version.
Here are the steps to reproduce:

1. create a dummy spring boot project with "spring-boot-starter-actuator", "spring-boot-starter-web" and "chaos-monkey-spring-boot" as the dependencies in the pom.xml file.
2. create one class annotated as a "RestController" with some get or post methods.
3. create one class annotated as a "Service" with some dummy method.
4. implement the "BeanPostProcessor" interface and override the default methods implementations (you can just return the bean inside the method) annotate the class with "Component".
5. try to run the application

**Comment by Bknisan** [comment]
after digging into previous issues I see this one is a duplication of  #199.
I see the last merge provided a fix for this #200.
somehow the latest version I can consume is "2.3.2" and the errors still occur there.
can you advise? @WtfJoke

**Comment by WtfJoke** [comment]
>  I can consume is "2.3.2" and the errors still occur there.
> can you advise? @WtfJoke

We havent put out a release since this fix. You can use the latest snapshot 2.3.2-SNAPSHOT and verify if the error gets solved.  See here the docs for how to use snapshots --> https://codecentric.github.io/chaos-monkey-spring-boot/#snapshots

**Comment by Bknisan** [comment]
solved in snapshot

**Comment by WtfJoke** [comment]
Wanted to let you know that we just released 2.3.9, which contains the fix, see https://github.com/codecentric/chaos-monkey-spring-boot/releases/tag/v2.3.9
