### ISSUE TITLE
Demo app not running

### ISSUE THREAD

**Issue by ranajit-jana** [codecentric/chaos-monkey-spring-boot#21]
when starting demo app
getting error as below.

No changes was done on the code.

<code>
no main manifest attribute, in chaos-monkey-demo-app-2.0.0-SNAPSHOT.jar 
</code>

**Comment by ranajit-jana** [comment]
If it is running in your local probably it may be working. Please share the way to start the demo application.

I have done the  following steps.`
```

git  clone ...
git pull origin 1.5.x

mvn clean install

cd chaos-monkey-demo-app/target

java -jar chaos-monkey-demo-app-1.5.0-SNAPSHOT.jar

```


so with the branch  1.5.x or master i am getting same error.

additional parameter if needed to be passed to start this will help.

**Comment by MrBW** [comment]
Error fixed! Please check out my latest changes...
It was my mistake, the Spring Boot Maven Plugin was configured wrong for chaos-monkey-demo-app. 

```
java -jar chaos-monkey-demo-app-1.5.0-SNAPSHOT.jar --spring.profiles.active=chaos-monkey
```
Thx for the issue!

Bye,
Benjamin
