### ISSUE TITLE
Interested in ability to enable/disable chaos via feature flags?

### ISSUE THREAD

**Issue by checketts** [codecentric/chaos-monkey-spring-boot#212]
Currently you can configure CM4SB via properties and acutator endpoints. However, I would like to contribute code that would leverage the Unleash feature switch library to enable/disable chaos.

For example, the workflow I want to use is this:

- Unleash will be an optional dep for CM4SB
- Unleash configuration will check if the Unleash class is on the classpath
- If the user enables a feature flag (myApp.controllers.chaos) then chaos will happen, then they can turn it off to disable the chaos.

Would a PR offering this support be welcome?

**Comment by checketts** [comment]
@WtfJoke Sorry to bump this issue. But I would really love to contribute a PR for this if it isn't too out of scope for this project. I'm happy to clarify my usecase if you like.

Here are some benefits why I prefer feature flags over actuator endpoints:

* Since the service pulls in their flag states, we can be sure that each system in a cluster has the same configuration
* Using feature flags I can enable chaos for a subset of my requests. Specifically, I can enable chaos for myself without impacting others
* The UI for enabling/disable chaos settings is a bit more straight forward since it largely can just be a toggle that is turned on or off.

![image](https://user-images.githubusercontent.com/416063/114650153-f4289c00-9c9e-11eb-9b41-b59942ef49ef.png)

**Comment by WtfJoke** [comment]
Hi @checketts 

Sorry for the late reply, currently I'm quiet occupied :see_no_evil: 

Although I like the idea and can see a benefit, I'm a bit worried about the maintenance efforts after a potential PR is merged. And we should then probably support other feature flag libraries such as Togglz. 



>     * Using feature flags I can enable chaos for a subset of my requests. Specifically, I can enable chaos for myself without impacting others

Can you eloborate a bit more how that would work?

**Comment by checketts** [comment]
I completely understand concerns around scope increase/maintenance. In fact the way I would approach it would abstract the logic so togglz (or commercial offerings like Launch Darkly) could easily be plugged in.

So the way Unleash works (and I assume most modern feature switch services do as well) is to include a 'context' when checking if a toggle is enabled. That context can include data like the user's ID, or other metadata like roles or preferred languages, you can add whatever you like.

Essentially the call looks like this, the `isEnabled` call uses a `ContextProvider` to lookup the user details:

```java
if(featureService.isEnabled("includeChaos")) {
  //add chaos to request
}
``` 

That allows approaches like enabling chaos for specific users (testers or automation) or other approaches.

**Comment by checketts** [comment]
In the PR #220 I added a demo app: https://github.com/checketts/chaos-monkey-spring-boot/tree/add-toggle-lookup-capabilities/demo-apps/chaos-monkey-demo-app-unleash-toggles

Now that I've written it up and played with it, the Unleash specific code is quite small (and could even be left out of Chaos Monkey) if that is preferred:


```java
public class UnleashChaosToggles implements ChaosToggles {
  private final Unleash unleash;

  public UnleashChaosToggles(Unleash unleash) {
    this.unleash = unleash;
  }

  @Override
  public Boolean isEnabled(String toggleName) {
    return unleash.isEnabled(toggleName);
  }
}
```

Configuration:

```java
  @Configuration
  @ConditionalOnClass(Unleash.class)
  @ConditionalOnProperty(value = "chaos.monkey.toggle.unleash.enabled", matchIfMissing = true)
  static class UnleashChaosConfiguration {

    @Bean
    @ConditionalOnMissingBean
    @ConditionalOnBean(Unleash.class)
    public ChaosToggles unleashChaosToggles(Unleash unleash) {
      return new UnleashChaosToggles(unleash);
    }
  }
```

**Comment by checketts** [comment]
@WtfJoke Are there any other issues you would like prioritized before releasing this? I would be happy to look into them.

**Comment by WtfJoke** [comment]
Nothing in particular to be honest. 

I still need to review #229.

Whats on my list (not sure if it goes to the next release or the one afterswards):
- Spring Boot 2.5.0 update
- Improving the release process (I made some experiments like generating a github release with changelog). 
- And I had a look how a CPU Assault could work (I think fibonacci would be a good way to generate load, you can do that if you like)
