### ISSUE TITLE
Repository watcher and exception assault is not working

### ISSUE THREAD

**Issue by rd-evgeni-ivanov** [codecentric/chaos-monkey-spring-boot#217]
When using Chaos Monkey 2.3.* and the latest Chaos Toolkit, an experiment with a repository watcher and an exception assault is not throwing the exception.
With Chaos Monkey 2.2.0 the same experiment is working properly.
This can be reproduced with https://github.com/TechPrimers/defensive-demo

**Comment by WtfJoke** [comment]
Thanks for the info. It seems to not working when activated with actuator. Seems to be caused by the fix of #200

**Comment by WtfJoke** [comment]
Should be working with the next release again, will notify you here as soon as its published

**Comment by WtfJoke** [comment]
Version 2.3.10 is published, give it a try and let me know. :)
