### ISSUE TITLE
External dependency Jar file broken in 2.3.9 release

### ISSUE THREAD

**Issue by georgeharley** [codecentric/chaos-monkey-spring-boot#218]
## Expected Behavior

Using the version 2.3.9 external dependencies Jar (chaos-monkey-spring-boot-2.3.9-jar-with-dependencies.jar) to introduce chaos attacks to an existing executable Spring Boot Jar should work [as described in the documentation](https://codecentric.github.io/chaos-monkey-spring-boot/latest/#_external_dependency_jar_file).

## Current Behavior

With the 2.3.9 external dependencies Jar there is no evidence that the target Spring Boot application is affected in any way. There is no "ready to do evil!" message in the application logs and the configured attacks do not occur.

## Possible Solution

The problem appears to be that the 2.3.9 external dependencies Jar has been built with an incorrect **META-INF/spring.factories** file. It ought to pull in the class `de.codecentric.spring.boot.chaos.monkey.configuration.ChaosMonkeyConfiguration` to the Spring Boot autoconfiguration but instead that crucial configuration class is not actualy mentioned. Instead, the **META-INF/spring.factories** file references thousands of Spring classes. 

## Steps to Reproduce

Try following the steps in [section 2.2](https://codecentric.github.io/chaos-monkey-spring-boot/latest/#_external_dependency_jar_file) of the official documentation using **chaos-monkey-spring-boot-2.3.9-jar-with-dependencies.jar**. The steps will fail with no sign of any CM4SB activity. 

Try replacing the **META-INF/spring.factories** file in the external dependencies Jar with the one contained in the 2.3.2 external dependencies Jar and then repeat the steps: things should now work.

Note: the **META-INF/spring-configuration-metadata.json** file included in the 2.3.9 external dependencies Jar also seems to be incorrect. While it does not have any bearing on the problem described in this issue it is perhaps further evidence that something odd happened when **chaos-monkey-spring-boot-2.3.9-jar-with-dependencies.jar** was assembled?

**Comment by WtfJoke** [comment]
Thanks @georgeharley for your detailed report.

I made some additional tests during the last few evenings. It wasnt happening with spring boot 2.4.4 and 2.3.2. 

On my windows machine with 2.3.9 they were two spring.factories file in the jar. The one you mention (which is the default of spring boot) and the chaos monkey one, however on my linux machine I had only the spring boot factories file. 

Although it seems likely, I dont think this is a build issue as we follow the documented approach as far as I can tell.

I will experiment more with the just released 2.3.10 version (my first test was sucessfull on my linux machine).

**Comment by georgeharley** [comment]
> On my windows machine with 2.3.9 they were two spring.factories file in the jar. The one you mention (which is the default of spring boot) and the chaos monkey one, however on my linux machine I had only the spring boot factories file.

I'm a bit confused by that statement as I thought there was only the one released CM4SB 2.3.9 external dependencies Jar under discussion - the [chaos-monkey-spring-boot-2.3.9-jar-with-dependencies.jar](https://repo1.maven.org/maven2/de/codecentric/chaos-monkey-spring-boot/2.3.9/chaos-monkey-spring-boot-2.3.9-jar-with-dependencies.jar) file in Maven Central. That contains a single **META-INF/spring.factories** entry which does not look right (i.e. it is the default Spring Boot one rather than the expected one which references the `ChaosMonkeyConiguration` class). 

Just tried using [chaos-monkey-spring-boot-2.3.9-jar-with-dependencies.jar](https://repo1.maven.org/maven2/de/codecentric/chaos-monkey-spring-boot/2.3.9/chaos-monkey-spring-boot-2.3.9-jar-with-dependencies.jar) against a Spring Boot 2.3.10 application and it still fails as described in this issue's initial comment.

Updating the released chaos-monkey-spring-boot-2.3.9-jar-with-dependencies.jar to use the **META-INF/spring.factories** file included in [chaos-monkey-spring-boot-2.3.2-jar-with-dependencies.jar](https://repo1.maven.org/maven2/de/codecentric/chaos-monkey-spring-boot/2.3.2/chaos-monkey-spring-boot-2.3.2-jar-with-dependencies.jar) restores things to the expected working behaviour once again.

**Comment by WtfJoke** [comment]
> I'm a bit confused by that statement

I should have been more precise. I  also should have mentioned that I have rebuild those jars locally and my whole comment/testing refered to those locally build jars (which arent published). I am aware of that the published jar is broken (thanks to your issue of course :D)

So what I meant is, that when I locally upgraded the spring boot version of chaos monkey (to either 2.3.10 or 2.4.4)  it worked (whereas with 2.3.7, 2.3.9 it didnt work).

I hope I didnt confuse you any further by now 😅 

I'll will make an additional test and will soon merge spring boot 2.3.10 and we'll see if the published snapshot jar will have the correct spring.factories file again.

**Comment by WtfJoke** [comment]
It something in the maven configuration. `./mvnw install` breaks the jar. 

When I execute `./mvnw verify` the resulting jar is correct.  ✔️ 
When I execute `./mvnw install` the jar gets "corrupted" ❌

**Comment by WtfJoke** [comment]
Now it should be fixed with #222 and I just triggered a release of 2.3.10.  I locally tested it. Please also test it and confirm that its (finally) solved. Took longer than expected 🙈

**Comment by georgeharley** [comment]
It is working great with the external dependencies Jar from the 2.3.10 release. Will close the issue now. 

Thank you very much @WtfJoke for taking the time to fix this 🙇‍♂️
