### ISSUE TITLE
"killApplicationActive": true is not working for spring webflux aplication

### ISSUE THREAD

**Issue by soumyadeep-saha** [codecentric/chaos-monkey-spring-boot#228]
**"killApplicationActive": true** is set to **true** for all  service annotated classes, but still my application  running in intellij is not shutting down. 
My application is in **spring boot 2.4.2** and i am using **chaos-monkey-web-reactive-app** and **chaos-monkey-web-reactive-app** as i am using spring webflux
I have given the **pom.xml**, **active profiles** and **chaosmonkey** status details.

### pom.xml
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webflux</artifactId>
        </dependency>
            <dependency>
            <groupId>de.codecentric</groupId>
            <artifactId>chaos-monkey-web-reactive-app</artifactId>
            <version>2.4.5</version>
        </dependency>
  <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>**spring-boot-starter-parent**</artifactId>
        <version>2.4.2</version>
        <relativePath/>
    </parent>

### Running with profile
-Dspring.profiles.active=default,chaos-monkey

### Status Of ChaosMonkey
http://localhost:6060/cartcomp/management/chaosmonkey
{
  "chaosMonkeyProperties": {
    "enabled": true
  },
  "assaultProperties": {
    "level": 1,
    "latencyRangeStart": 5000,
    "latencyRangeEnd": 6000,
    "latencyActive": false,
    "exceptionsActive": false,
    "exception": {
      "type": null,
      "arguments": null
    },
    "killApplicationActive": true,
    "memoryActive": false,
    "memoryMillisecondsHoldFilledMemory": 90000,
    "memoryMillisecondsWaitNextIncrease": 1000,
    "memoryFillIncrementFraction": 0.15,
    "memoryFillTargetFraction": 0.25,
    "runtimeAssaultCronExpression": "OFF"
  },
  "watcherProperties": {
    "controller": false,
    "restController": false,
    "service": true,
    "repository": false,
    "component": false
  }
}

**Could you please help me with the above query?**

**Comment by WtfJoke** [comment]
Hi @soumyadeep-saha 

1. You have a small mistake in your pom.xml. The dependency is `chaos-monkey-spring-boot` even on a webflux. The `chaos-monkey-web-reactive-app` is actually the demo app, which were testing the functionality. With the next version we wont publish these artifacts anymore (see #224)
```
<dependency>
  <groupId>de.codecentric</groupId>
  <artifactId>chaos-monkey-spring-boot</artifactId>
  <version>2.4.5</version>
</dependency>
```

2.  The Kill Application and Memory Assault can only be triggered using either a Scheduled Cron Expression (see https://codecentric.github.io/chaos-monkey-spring-boot/latest/#_properties `chaos.monkey.assaults.runtime.scope.assault.cron.expression`) or calling the rest endpoint `/actuator/chaosmonkey/assaults/runtime/attack` (POST). So either configure a cron expression or try to call the rest endpoint and see if your app gets killed :)

The docs are not very well in this regard, I opened #230 to track this.

Let me know if this works. I tested it in a sample application and for me it worked.

**Comment by soumyadeep-saha** [comment]
Hi @WtfJoke 
Thanks for your response:)
actuator/chaosmonkey/assaults/runtime/attack (POST) with no body in POST call seems to kill the application now

But still I have few questions, could you please help me out with those please
1. Can we make KillApplication method specific like the way we do for latency?
2. Can this API **actuator/chaosmonkey/assaults/runtime/attack (POST)** is privileged to take a JSON body?
3.  Can you please provide an example of how to use **chaos.monkey.assaults.runtime.scope.assault.cron.expression** for Kill Application and Memory Assault each separately?
**Could you please help me with the above 3 questions**


### chaos.monkey.assaults.level not working as expected
My understanding is if this **chaos.monkey.assaults.level** is set to 3, then for an exception scenario, it means first 3 calls(call number 1, 2, 3) will be successful, next 3 calls(4, 5, 6) will give exception, then again next 3 calls(call number 7, 8, 9) will be successful and again next 3 calls(10,  11, 12) will give exception. But this is not working like this. Can you please suggest?

**Comment by WtfJoke** [comment]
Glad it works. :)

Please ask your questions in stackoverflow (we try to keep github issues for issues only). However I'll answer them now
1. We probably could, not sure if it makes much sense, though. 
2. It currently doesnt take a body
3. You can only define a cron expression for both assaults, but not separetly (https://github.com/codecentric/chaos-monkey-spring-boot/pull/183 wanted to change that, but it didnt got to the point it could be merged).

About the assaults.level its not exactly like you describe it.
Its about every x request. So level 3 means about every 3. request. 

So if you make 6 requests about 3 get assaulted (but not in the order, more like 1 success, 2, success, 3rd wrong. Its not deterministically every 3rd.

But the same is also written in the [docs](https://codecentric.github.io/chaos-monkey-spring-boot/latest/#_properties)
