### ISSUE TITLE
spring boot app in Azure spring cloud, fails to start with chaos monkey profile. due to unresolvable circular reference. 

### ISSUE THREAD

**Issue by antonben007** [codecentric/chaos-monkey-spring-boot#231]
spring boot app in Azure spring cloud, fails to start with chaos monkey profile. due to unresolvable circular reference.

getting the following error: 
org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'chaosMonkeyRequestScope': Requested bean is currently in creation: Is there an unresolvable circular reference? 
I am getting this with version 2.3.10 , and even the older version  2..31 too.

**Comment by checketts** [comment]
Do you have a similar situation as described in #232 ? (FactoryBean is annotated with @Component)

**Comment by WtfJoke** [comment]
Would be great to have a full stacktrace or even better a small demo app :)
