### ISSUE TITLE
Unresolvable circular reference error when FactoryBean is annotated with @Component

### ISSUE THREAD

**Issue by mmerla** [codecentric/chaos-monkey-spring-boot#232]
## Expected Behavior
Chaos-monkey-spring-boot should work when a class implements ```org.springframework.beans.factory.FactoryBean``` and is annotated with ```@Component```. This is similar to #199. 

## Current Behavior
When a class implements ```org.springframework.beans.factory.FactoryBean``` and is annotated with ```@Component``` during startup, there is an error
```FactoryBean threw exception from getObjectType, despite the contract saying that it should return null if the type of its object cannot be determined yet``` 
```org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'chaosMonkeyRequestScope': Requested bean is currently in creation: Is there an unresolvable circular reference?```

## Possible Solution

Exclude implementation of ```org.springframework.beans.factory.FactoryBean``` in the ```springHooksPointsCut``` in the ```ChaosMonkeyBaseAspect``` class.

**Comment by WtfJoke** [comment]
Thank you @mmerla for reporting the issue and providing a possible solution. If you want, feel free to open a PR

**Comment by mmerla** [comment]
@WtfJoke Thanks for looking at this. I will be opening a PR soon.
