### ISSUE TITLE
Enable/Disable Endpoint should show duration

### ISSUE THREAD

**Issue by WtfJoke** [codecentric/chaos-monkey-spring-boot#258]
Both if it were disable and if it is still active. Seeing something like: `durationMinutes: 180` makes for some simple math so the caller doesn't have to worry about when something was enabled (regardless of timezone).

Duration Is probably a poor name. `minutesActive` might be clearer. It would keep counting up if it hasn't been disabled. 

Feel free to ignore this idea though if it distracts from the endpoint's purpose.

_Originally posted by @checketts in https://github.com/codecentric/chaos-monkey-spring-boot/issues/246#issuecomment-890033899_

**Comment by WtfJoke** [comment]
I like the idea. The feature is probably not that important but a nice addition.
It would make sense to have a good readable format for humans. I could imagine an output like "x hours x minutes x seconds"

**Comment by MatthewBerk** [comment]
I am currently working on some other things at the moment but would still like to take on this issue!

**Comment by MatthewBerk** [comment]
More things have come up in this past week, so I will get to working on this as soon as I can! Thank you for assigning it to me!

**Comment by WtfJoke** [comment]
No need to appologize :)
