### ISSUE TITLE
SpringRepositoryAspect does not seem to be created by the auto-configuration

### ISSUE THREAD

**Issue by corsin** [codecentric/chaos-monkey-spring-boot#26]
In the auto-configuration class `ChaosMonkeyConfiguration` all the aspect beans for the different Spring component types are created. The bean `SpringRepositoryAspect` seems to be missing though. Hence the Spring Boot Chaos Monkey never intercepts calls to `@Repository` components.

**Comment by MrBW** [comment]
Thx for the hint...will check this!

**Comment by corsin** [comment]
Excellent. Thanks!
