### ISSUE TITLE
chaos-monkey-spring-boot is not runnning

### ISSUE THREAD

**Issue by venkiradkris** [codecentric/chaos-monkey-spring-boot#28]
Hi - Please check/suggest/help. Thanks.

cd /usr/share/chaos/chaos-monkey-spring-boot-master/chaos-monkey-spring-boot/
mvn clean install
BUILD SUCCESS

cd /usr/share/chaos/chaos-monkey-spring-boot-master/chaos-monkey-spring-boot/target
java -jar chaos-monkey-spring-boot-2.0.1-SNAPSHOT.jar --spring.profiles.active=chaos-monkey
Issue: no main manifest attribute, in chaos-monkey-spring-boot-2.0.1-SNAPSHOT.jar

Regards
Venkat

**Comment by deelthor** [comment]
Hey @venkiradkris,

Thanks for the feedback. chaos-monkey-spring-boot-2.0.1-SNAPSHOT.jar is not an executable jar file. There is a [demo-app](https://github.com/codecentric/chaos-monkey-spring-boot/tree/master/chaos-monkey-demo-app) within in the project which you can use to experiment with the chaos monkey. Just execute the same maven commands in chaos-monkey-demo-app.
