### ISSUE TITLE
Spring Webflux application using Functional Web framework fails to startup 

### ISSUE THREAD

**Issue by shajeni72** [codecentric/chaos-monkey-spring-boot#285]
Spring Webflux application using Functional Web framework fails to startup. 

My application uses functional web framework https://spring.io/blog/2016/09/22/new-in-spring-5-functional-web-framework. Upon adding CMSB the application fails to startup.

Does Chaos Monkey supports spring webflux functional web ?

## Current Behavior
org.springframework.boot.web.reactive.context.AnnotationConfigReactiveWebServerApplicationContext
java.lang.IllegalStateException: No routes registered. Register a route with GET(), POST()

**Comment by WtfJoke** [comment]
Hi @shajeni72 

As far as I know it supports spring reactive stack.
There is also a small [demo app](https://github.com/codecentric/chaos-monkey-spring-boot/tree/main/demo-apps/chaos-monkey-web-reactive-app).

You might wanna check it out. 
If you have a small demo app, which reproduces the mentioned error it would be great.

**Comment by shajeni72** [comment]
Thanks for sharing the demo app. After taking a closer look it made sense that issue was related to https://github.com/codecentric/chaos-monkey-spring-boot/issues/189

My app uses custom annotation to register the routes and the custom annotation did not get picked up as the bean was converted a CGLIB bean. 

I resolved by adding this

```
if (activeProfileisChaosMonkey) {
                methods = ClassUtils.getUserClass(bean).getMethods();
            } else {
                methods = bean.getClass().getMethods();
            }
```
