### ISSUE TITLE
Separate the pointcut and aspect(advice), and allow user to override them

### ISSUE THREAD

**Issue by ttddyy** [codecentric/chaos-monkey-spring-boot#287]
Hello,

We have faced a problem with proxying a `@Component` that has **final methods**.  
Since CGLIB cannot proxy the final methods (final classes was handled by #188), it produces a log like this:

```
org.springframework.aop.framework.CglibAopProxy@263 - Unable to proxy interface-implementing method [public final void com.example.Foo.execute(com.example.Bar)] because it is marked as final: Consider using interface-based JDK proxies instead!
```
Then, the component was not properly dependency injected and failed with NPE at runtime.

The underlying problem is that the `SpringComponentAspect` and its friends are too generalized to grab many of the application's beans. Yet, there is no control available to users.

We want to have a control for excluding certain classes or packages for proxying. Or, maybe proxy only the specific set of beans.

One way is to override the aspect bean(e.g. `SpringComponentAspect`). However, since it is an aspect that contains both the pointcuts and the proxy logic(advice), the overriding custom bean needs to copy/paste the advice from the original bean if I were to change only the pointcut. This is not an ideal approach.

I would like to suggest, rather than using Aspect, use the underlying spring infrastructure for the AOP.
Since `chaos-monkey-spring-boot` is a library, it is preferable to provide a flexible approach rather than an aspect for creating proxies.

The `DefaultAdvisorAutoProxyCreator` allows dynamically creating proxies by taking advisors.

So, for example with sudo code:

```java

// just a marker interface for the advisor to the component classes
public interface ComponentAdvisor implements Advisor {
}

// just a marker interface for the advice to the component classes
public interface ComponentAdvice implements Advice {
}
```

```java
@ConditionalOnMissingBean
@Bean
public ComponentAdvice componentAdvice() {
  // the advice logic for @Component beans. e.g. introduction/interceptor
}

@ConditionalOnMissingBean
@Bean
public ComponentAdvisor componentAdvisor(ObjectProvider<ComponentAdvice> advices) {
   // provide default pointcut for @Component beans
}

@ConditionalOnMissingBean
@Bean
public DefaultAdvisorAutoProxyCreator componentProxyCreator(ObjectProvider<ComponentAdvisor> advisors) {
  // create proxy creator based on the advisors for @Component beans
}
```

This way, since these beans are `@ConditionalOnMissingBean`, the user can provide own implementation to override the default ones independently.

**Comment by WtfJoke** [comment]
Hi @ttddyy 

Thank you for your detailed issue. I'll understand the difficulties you have. 

Separating Advices and PointCut most likely would work like you describe, but im not sure if we should go this direction.

However with our latest release [2.5.4](https://github.com/codecentric/chaos-monkey-spring-boot/releases/tag/v2.5.4) we support [bean watchers](https://codecentric.github.io/chaos-monkey-spring-boot/latest/#_alternative_bean_watcher). The support is a bit limited compared to other watchers. But it might solve the issue you have. 

Can you give it a try and give us feedback?

**Comment by ttddyy** [comment]
@WtfJoke Thanks for the pointer.

At a quick glance, the `watchedCustomServices` seems selectively specify which ones to proxy.
This probably is ok when target components are only a few.
On the other hand, if there are many components, it would be nice to have exclusion.


I just created a simple repro project to show the issue with a final method.
https://github.com/ttddyy/chaos-monkey-spring-boot_gh-287

Since proxying the final method is a limitation of the CGLIB (or Java spec), I don't think there is an easy way to avoid it.

If current aspects are not easy to modify for users, probably providing a way to exclude components would be necessary.
For example, provide an annotation(invasive to the code), a property to list components to exclude, etc.

I'll file a separate ticket for that.

**Comment by ttddyy** [comment]
I just tried the `chaos.monkey.assaults.watchedCustomServices` property but unfortunately it doesn't work.

I did not list the `GreetingService` on the `watchedCustomServices` property, but I still see this log message:
```
2021-12-03 12:04:05.028 DEBUG 72174 --- [           main] o.s.aop.framework.CglibAopProxy          : Final method [public final java.lang.String com.example.demochaosmonkey.GreetingService.greet()] cannot get proxied via CGLIB: Calls to this method will NOT be routed to the target instance and might lead to NPEs against uninitialized fields in the proxy instance.
```

This means it is still creating a proxy on the `GreetingService` bean.
By quickly looking
https://github.com/codecentric/chaos-monkey-spring-boot/blob/main/chaos-monkey-spring-boot/src/main/java/de/codecentric/spring/boot/chaos/monkey/watcher/aspect/SpringServiceAspect.java#L47-L50

I don't think the pointcut expression is considering any values specified in `watchedCustomServices`.(I don't know that's even possible or not) So, it still simply creates proxies against all beans (For example `@Service` beans for this aspect).

Probably `watchedCustomServices` is used in a different layer. So, this doesn't work to avoid proxying a class with final methods.

**Comment by F43nd1r** [comment]
@ttddyy bean watchers and `watchCustomServices` are two separate things. Use`chaos.monkey.watcher.beans` instead.

**Comment by manishrathi4** [comment]
I am facing the same issue. Below are various scenarios where you see this error "Could not generate CGLIB subclass of class xxxxx". The error happens as you try to start the application, and application doesn't boot.

- class with private or final method
- final class

Is there a solution or workaround? Are we expecting a fix in the next version of the framework.
