### ISSUE TITLE
Provide exclusion to assaults

### ISSUE THREAD

**Issue by ttddyy** [codecentric/chaos-monkey-spring-boot#290]
The `watchedCustomServices` property can specify which components to assault.  It is good when target components are only a few.
On the other hand, if there are many components, it would be nice to have exclusion.

For example, due to the limitation of proxying a component with final method(#287), I need to exclude some of the components.

When those classes with a final method come from the application, it is easy to modify for a workaround. However, if those components come from an external library, it is hard to change them.

Hence, I think it is very important for Chaos Monkey Spring Boot to provide a way to exclude such beans.

**Comment by WtfJoke** [comment]
Sounds like a great idea, thank you for sparking it :)
