### ISSUE TITLE
scheduler Bean is interfering with Beans from other libs

### ISSUE THREAD

**Issue by dreyinger** [codecentric/chaos-monkey-spring-boot#292]
## Expected Behavior

The Bean `scheduler` could have a more specific name to avoid Bean name collisions.

## Current Behavior

When using `chaos-monkey-spring-boot` library together with [db-scheduler](https://github.com/kagkarlsson/db-scheduler) there are two beans with the name `scheduler`. This makes chaos-monkey unusable in the latest version.

## Possible Solution

Rename the Bean/method to chaosMonkeyScheduler

## Steps to Reproduce

Create a project with [db-scheduler](https://github.com/kagkarlsson/db-scheduler) and chaos-monkey-spring-boot library and start the application. The application won't start because of the Bean name collision.

**Comment by WtfJoke** [comment]
Fixed with #293
