### ISSUE TITLE
Rename Integration(Tests) to IntegrationTest

### ISSUE THREAD

**Issue by WtfJoke** [codecentric/chaos-monkey-spring-boot#295]
Undo #177 as maven surefire doesnt execute these tests default and we needed to include it using a property.

**Comment by anurag-rajawat** [comment]
Hi @WtfJoke I would like to work on this issue? Can you assign this to me?

**Comment by WtfJoke** [comment]
Hey @anurag-rajawat sure, I'll asign it to you. Feel free to ask questions if you encounter any issues.
