### ISSUE TITLE
webClient doesn't work when chaos.monkey.enable is false

### ISSUE THREAD

**Issue by yangbongsoo** [codecentric/chaos-monkey-spring-boot#304]
## Expected Behavior
I hope that webClient work well in afterPropertiesSet.

## Current Behavior
My `chaos.monkey.enable` property value is false.
```
chaos:
  monkey:
    enabled: false
```

But When I start application, webClient doesn't work in bean load stage.
```java
@Component
@RequiredArgsConstructor
public class ProblemComponent implements InitializingBean {

	private final ApiClient apiClient;

	// TODO: problem
	@Override
	public void afterPropertiesSet() {
		System.out.println("ProblemComponent : Targets afterPropertiesSet start");
		try {
			String responseBody = apiClient.call().block();
			System.out.println(responseBody);
		} catch (Exception e) {
			throw new RuntimeException(e);
		}
	}
}
```

## Possible Solution
I have no idea whether It is bug or intended fail.
When I remove `assaultWebClient.run();` and `this.assaultInjectionService.assaultAllWebClient();` in WebClientConfig, the problem was solved. but this solution is not what I want. Many other webClients use this `customizeReactorClientHttpConnector` method.
```java
private ReactorClientHttpConnector customizeReactorClientHttpConnector(
	ReactorResourceFactory reactorResourceFactory,
	int connectionTimeoutMillis,
	int readTimeoutMillis,
	Runnable assaultWebClient
) {
	return new ReactorClientHttpConnector(reactorResourceFactory, defaultHttpClient -> {
		HttpClient httpClient = defaultHttpClient
			.option(ChannelOption.CONNECT_TIMEOUT_MILLIS, connectionTimeoutMillis)
			.doOnConnected(connection -> {
				connection.addHandlerLast(
					new ReadTimeoutHandler(readTimeoutMillis, TimeUnit.MILLISECONDS)
				);
				// assaultWebClient.run();
				// this.assaultInjectionService.assaultAllWebClient();
			});
		return httpClient;
	});
}
```

please give me some advise.

## Steps to Reproduce

[I made reproduce demo sample project.](https://github.com/yangbongsoo/webclient-problem-cm4sb#webclient-issue-when-using-cm4sb)
step1 : git clone that project
step2 : start `com.toy.target.TargetServer` application
step3 : start spring MainApplication

**Comment by F43nd1r** [comment]
Thanks for the reproducer, this is a very unfortunate side effect. Seems like the bean factory has problems initializing our aspects in the webclient thread and runs into a deadlock. We're still investigating how this could be fixed.

**Comment by F43nd1r** [comment]
This issue is a deadlock between synchronization in beanfactory and webclient. I was able to reproduce the issue with simpler code:
```
  private final Object lock = new Object();

  @Override
  public void afterPropertiesSet() {
    System.out.println("ProblemComponent : Targets afterPropertiesSet start");
    try {
      Thread thread = new Thread(() -> {
        applicationContext.getBean(SpringServiceAspect.class);
        synchronized (lock) {
          lock.notify();
        }
      });
      thread.start();
      synchronized (lock) {
        lock.wait();
      }

      System.out.println("ProblemComponent: Finished");
    } catch (Exception e) {
      throw new RuntimeException(e);
    }
  }
}
```

This deadlock can be avoided in several ways, e.g.
 - manually modify the bean load order (in your reproducer this would mean `@DependsOn({"serviceAspect", "metrics", "startupTimeMetrics"})` on `ApiClient`)
 - don't make the network call in a separate thread (e.g. use `RestTemplate` instead of `WebClient`)
 - don't use `WebClient` during bean creation (e.g. replace `afterPropertiesSet` with `@EventListener(ApplicationReadyEvent.class)`

It seems like there is no way to prevent this issue from our side.

**Comment by yangbongsoo** [comment]
1. webClient without CM4SB can be used in afterPropertiesSet. no deadlock problem.
2. webClient using CM4SB makes deadlock because of bean factory and CM4SB aspects

Is it right??

**Comment by F43nd1r** [comment]
> 1. webClient without CM4SB can be used in afterPropertiesSet. no deadlock problem.
> 
>     2. webClient using CM4SB makes deadlock because of bean factory and CM4SB aspects
> 
> 
> Is it right??

It's not just using a webclient that is the problem. It's using a webclient that has bean dependencies which get initialized in another thread.
But yes, in the end the exact code you have does not and will never work with chaosmonkey out of the box, it's impossible to fix on our side.

I have given several workarounds for you to choose from, I hope one of those works for you. We think the third workaround is the best option in this case.

**Comment by yangbongsoo** [comment]
thank you !!
