### ISSUE TITLE
Support Spring Data's Repository interface

### ISSUE THREAD

**Issue by jonatan-ivanov** [codecentric/chaos-monkey-spring-boot#317]
As far as I know (and as it is documented), the repository watcher (`chaos.monkey.watcher.repository`) only supports the `@Repository` stereotype.
There are use-cases where repositories are created without the user annotating them with the `@Repository` annotation.
E.g.: Spring Data JPA, Spring Data Rest, etc. generates implementation for interfaces that extend `org.springframework.data.repository.Repository` (or one of it's sub-interface like `CrudRepository` or `PagingAndSortingRepository`). These repositories are not watched by the repository watcher.

## Expected Behavior
`org.springframework.data.repository.Repository` instances should be watched if `chaos.monkey.watcher.repository` is set to `true`.

## Current Behavior
`org.springframework.data.repository.Repository` instances are not watched if `chaos.monkey.watcher.repository` is set to `true`.

## Possible Solution
I'm not very familiar with the internals of the projects but loosening the predicate that decides if a bean is watched or not during scanning should solve this (I guess).

## Steps to Reproduce
I think this is by-design but
[here's a reproducer](https://github.com/jonatan-ivanov/teahouse/blob/b52413338670cc6ab36e8c538831f769caadf753/water-service/src/main/resources/application.properties#L45); you need to re-enable chaos-monkey and set `chaos.monkey.watcher.repository=true`.

## Context (Environment)
I would like to inject errors and latency inside of my application close to the DB.
I'm using Spring Boot 2.7.0 (latest right now)

**Comment by F43nd1r** [comment]
I *think* this is supposed to already work that way, hence the bug label.

**Comment by jonatan-ivanov** [comment]
@F43nd1r I slimmed down one of your sample apps and it seems it does not work on my box: https://github.com/jonatan-ivanov/chaos-monkey-spring-boot/tree/spring-data-jpa-demo
(the [diff](https://github.com/codecentric/chaos-monkey-spring-boot/compare/main...jonatan-ivanov:spring-data-jpa-demo) is ugly so I recommend viewing the code, it's small)

A few notes with the sample:
- I removed `@Repository` from the `HelloRepository` interface, the `@Repository` stereotype is not for this use-case, it is not needed
- If you call the `http://localhost:8080/hello` endpoint (see: `HelloController`), chaos monkey does work: `chaos.monkey.watcher.rest-controller=true`
- If you call the `http://localhost:8080/helloes` (see: `HelloRepository`), chaos monkey does nothing: `chaos.monkey.watcher.repository=true`

Please let me know if you were able to repro the issue with this sample.

**Comment by F43nd1r** [comment]
Your demo works as expected for me. Please note that enabling multiple assaults (exception and latency) means one will be picked at random, so not every request fails.

**Comment by WtfJoke** [comment]
@jonatan-ivanov This is probably fixed with #335. It works with the latest snapshot (instructions [here](https://codecentric.github.io/chaos-monkey-spring-boot/latest/#_as_dependency). 

Would be great if you let usknow if it works in your use case as well :)
