### ISSUE TITLE
Does watchedCustomServices work for Repository sterotype?

### ISSUE THREAD

**Issue by keeplearningandtrying** [codecentric/chaos-monkey-spring-boot#323]
My observation is it doesn't.

**Comment by F43nd1r** [comment]
`watchedCustomServices` uses the method definition signature, meaning if a method is defined in a superclass (e.g. `CrudRepository` in this case) you'd have to put that class into `watchedCustomServices` instead.

If that is intended behaviour in this case is open for discussion. Calling @WtfJoke

**Comment by WtfJoke** [comment]
> If that is intended behaviour in this case is open for discussion. Calling @WtfJoke

Yeah we weren't very explicit about it, but imho thats the intended way.

**Comment by keeplearningandtrying** [comment]
@F43nd1r and @WtfJoke, thanks for the explain. I can verify that that is intended behavior.
