### ISSUE TITLE
ChaosMonkeyTaskScheduler shutting down spring boot application 

### ISSUE THREAD

**Issue by robinjacob** [codecentric/chaos-monkey-spring-boot#325]
One of the Kafka Consumer within my Spring Boot application is throwing an authentication error. This is causing the Spring Boot application to be shut down. I believe ChaosMonkeyTaskScheduler is shutting down the Spring Boot application. If I do not provide chaos-monkey in my spring profile during start up then Spring Boot Application starts fine although it shows authentication failure with the Kafka consumer during start up. I would like to ignore the Kafka authentication failure and have the Spring Boot application running with chaos-monkey. Please let me know if chaos monkey is shutting it down due to kafka authentication failure. Is there a way to get around it?

**Comment by F43nd1r** [comment]
> I believe ChaosMonkeyTaskScheduler is shutting down the Spring Boot application.

How did you get to this conclusion?

> Is there a way to get around it?

Please provide sources or a minimal reproducer for us to debug the issue. It is not clear from your description what is going on.
