### ISSUE TITLE
API Doc (OpenAPI Spec, etc.)

### ISSUE THREAD

**Issue by GerritRiesch94** [codecentric/chaos-monkey-spring-boot#326]
Hey is there any possibility to get a JSON Schema or better API Doc to rely on? Background of my question is, that I would like to make an WebUI tool to manage the configuration (Assaults, Watchers, enable/disable Chaos Monkey, etc.). Therefore it would be nice if I could do some input verification based on the API Doc. 

Thanks in advance for your support :)

**Comment by F43nd1r** [comment]
I've created a PR to create a springdoc group for chaosmonkey, but you can already view it with the current version by enabling the actuator support on springdoc.
```
springdoc:
  show-actuator: true
```

**Comment by GerritRiesch94** [comment]
Thank you for the hint. Tried it and worked fine.
