### ISSUE TITLE
inadequate step by step documentation

### ISSUE THREAD

**Issue by sachins50** [codecentric/chaos-monkey-spring-boot#34]
Hi codecentric team,

I am trying to explore chaos monkey for spring boot microservice which I have deployed on Pivotal web service. I deploy microservice with 'cf push' command and it reads definition from manifest.yml file.
If I have to implement chaos monkey then can you please provide detailed steps in my setup?
I do not have : application.properties and application.yml inside my app. So how do I employ this tool?
Also if I enable dependency in pom.xml - where do I copy chaos monkey library inside my app?
I am sorry for these questions - I am a newbie in this field. Appreciate your help on this.

Thanks - Sachin

**Comment by MrBW** [comment]
I have tried it with Pivotal Web Services and it works. Please check my gist and compare it to your setup. It is possible to use a application.properties or yml file with Pivotal WS.

Take a look at:
https://gist.github.com/MrBW/20b3b8ad88823a4dd3716de947942527

Please let me know if I can help you! You are welcome!

**Comment by MrBW** [comment]
No feedback since 21 days. Close this issue, if you need more help, you are welcome!
