### ISSUE TITLE
Ability to attack on only specific apis

### ISSUE THREAD

**Issue by satya2048** [codecentric/chaos-monkey-spring-boot#39]
Example say we have three apis /getproductdetails, saveproductdetails,/deleteproductdetails etc..now can we have the ability to attack on specific apis only not sure whether we have this feature as of now.

**Comment by MrBW** [comment]
Hi, nice idea and of course it's on our list. But currently the only way to manage this is byte-code-instrumentation. We will focus on this topic in one of our upcoming releases, currently we are changing some basics.
If you've any ideas please let me know!

**Comment by satya2048** [comment]
Hi MrBW thanks for the repsonse.Can you please elaborate on how to achieve the API specific attack using byte code instrumentation.thanks

**Comment by MrBW** [comment]
There is already a great project on github: https://github.com/mrwilson/byte-monkey
It's not done via AOP, but the topic is on our list.

**Comment by MrBW** [comment]
Add a task in our Chaos Board to develop this requested feature.
https://github.com/codecentric/chaos-monkey-spring-boot/projects/1#card-12369583
