### ISSUE TITLE
RestTemplate assault always throw HttpServerErrorException irrespective of exception specified in assault config

### ISSUE THREAD

**Issue by bunty-raghani** [codecentric/chaos-monkey-spring-boot#392]
In case of rest template assault, we should get the desired exception that was configured in assault config instead of HttpServerErrorException. This will be helpful to test different situations like Connection Timeout and so on.

## Expected Behavior
We should get the desired exception in case of RestTemplate assault instead of always getting HttpServerErrorException.

## Current Behavior
We always get the HttpServerErrorException with message:
`org.springframework.web.client.HttpServerErrorException$InternalServerError: 500 This error is generated by Chaos Monkey for Spring Boot: "{"error": "This is a Chaos Monkey for Spring Boot generated failure"}"`

## Steps to Reproduce
1. Configure ExceptionAssault with below config
`"exception": {
        "type": "org.springframework.web.client.HttpClientErrorException",
        "method": "<init>",
        "arguments": [
            {
                "type": "org.springframework.http.HttpStatusCode",
                "value": "404"
            }
        ]
    },`
2. Enable RestTemplate watcher
3. You will notice we always get HttpServerErrorException instead of HttpClientErrorException which was configured in assault. 

## Context (Environment)
In case of real world, this will be helpful to replicate scenarios like RequestTimeout, ConnectTimeout errors that are possible in case of RestTemplate calls.

**Comment by F43nd1r** [comment]
@tuxdevelop the code in question here is by you https://github.com/codecentric/chaos-monkey-spring-boot/blob/main/chaos-monkey-spring-boot/src/main/java/de/codecentric/spring/boot/chaos/monkey/watcher/outgoing/ChaosMonkeyRestTemplateWatcher.java#L57-L69. I don't really understand why it maps all configured exceptions to the same error response, maybe you can comment on that?

**Comment by F43nd1r** [comment]
Internal discussion result: This code was written before it was possible to configure parameters for thrown exceptions - which means it's most likely the correct approach to change it
