### ISSUE TITLE
usage for spring MVC application

### ISSUE THREAD

**Issue by ArjunSreepad** [codecentric/chaos-monkey-spring-boot#40]
can I use this to test a SPring MVC application instead of Spring BOOT?

**Comment by MrBW** [comment]
Chaos Monkey for Spring Boot is based on Spring Boot 1.5.x or 2.0.x, as long as Spring Boot is running your Spring MVC App, everything is ready to use the Chaos Monkey. I did not try the Chaos Monkey with a package WAR file. What is your stack look like? WAR file running in a Servlet container provided by a Application Server?

**Comment by ArjunSreepad** [comment]
Yea. WAR file running in a Servlet container provided by a Application Server?

**Comment by MrBW** [comment]
I tested it with Tomcat 9, Chaos Monkey Spring Boot 2.0.0 and with a MVC @Controller. It works out of the box :-)

So, the answer is YES you can use CMSB in a Spring MVC application running on a Application Server!

**Comment by MrBW** [comment]
![image](https://user-images.githubusercontent.com/6093565/44648265-c8b6ed00-a9e0-11e8-9833-4eafc7ca25f5.png)

**Comment by ArjunSreepad** [comment]
how to inject chaos monkey for a non spring boot application?
