### ISSUE TITLE
How to inject chaos monkey for a non spring boot application?

### ISSUE THREAD

**Issue by ArjunSreepad** [codecentric/chaos-monkey-spring-boot#42]
I have a spring mvc application. what are the different ways to inject chaos monkey for a non sprig boot application?

**Comment by MrBW** [comment]
If Spring Boot is not on board, the Chaos Monkey for Spring Boot cannot be used. But there are other chaos tools that can help you here.

For example (just Java): 
https://github.com/mrwilson/byte-monkey
https://blog.probablyfine.co.uk/2016/05/30/announcing-byte-monkey.html

A full list of Chaos Engineering tools can be found on GitHub: 
https://github.com/dastergon/awesome-chaos-engineering
