### ISSUE TITLE
Chaos-Monkey is not working when OpenTelemetry Agent is active

### ISSUE THREAD

**Issue by markusschaefer** [codecentric/chaos-monkey-spring-boot#482]
I have a simple Springboot Application with a RestController that Returns "Hello World" on a GET Request. I have activated chaos-monkey as described in the docs and everything is fine. When I add the ENV variable `JAVA_TOOL_OPTIONS="-javaagent:PATH/TO/opentelemetry-javaagent.jar` stops working.

## Expected Behavior
Chaos-Monkey should also work if an OpenTelemetry agent is running

## Current Behavior
Chaos-Monkey stops doing anything. There is no log entry.

## Steps to Reproduce
Create a Spring Boot Application with a simple RestController, Chaos-Monkey Dependency and OpenTelemety Agent

## Context (Environment)
springboot version: 3.2.5
Java 21

**Comment by denniseffing** [comment]
Hi!
Could you provide a minimal working example? I'll take a look then.

**Comment by markusschaefer** [comment]
I'm sorry. I can't reproduce the bug. Maybe it's gone with a Springboot or Opentelemetry Update.
