### ISSUE TITLE
Add support for Spring Boot 1.5.x

### ISSUE THREAD

**Issue by cgew85** [codecentric/chaos-monkey-spring-boot#5]
Since a lot of projects are still based on earlier versions of Spring Boot, adding support for them might be a good idea.

**Comment by MrBW** [comment]
Hi,

implementation for Spring 1.5.x is done...
I´ve created a first SNAPSHOT version for you, please take a look at:
https://oss.sonatype.org/content/repositories/snapshots/

<dependency>
  <groupId>de.codecentric</groupId>
  <artifactId>chaos-monkey-spring-boot</artifactId>
  <version>1.5.0-SNAPSHOT</version>
</dependency>

Documentation can be found here: 
https://codecentric.github.io/chaos-monkey-spring-boot/1.5.0-SNAPSHOT/

Bye,
Benjamin
