### ISSUE TITLE
Custom Exception support 

### ISSUE THREAD

**Issue by lipmanp** [codecentric/chaos-monkey-spring-boot#55]
Application may handle the specific exception when interacting with its down stream layers/components, to increase application resiliency.  But the current Exception Assault `public class ExceptionAssault implements ChaosMonkeyAssault` will throw RuntimeException only during attack, it will be hard for application level error handling. It would be good to have capability to specify exception type at experiment step, and the attack can raise it during the trial running.

let me know your thought, and I'm happy to contribute on it if the idea is agreeable.

**Comment by MrBW** [comment]
This feature would be awesome and I would like to do this! 

If I understood you correctly, the custom exception should be thrown at a defined time. We can ensure this with the new function using a CustomWatcher. This then triggers the Chaos Monkey as soon as a certain method is called. We can configure this dynamically at runtime via API Call of the Chaos Monkey, i.e. the ChaosToolkit can do this as well.

Thanks to the internal metrics of the Chaos Monkey we can also monitor whether this call and the custom exception have been triggered.

Does this reflect your idea and your use case?

**Comment by lipmanp** [comment]
Yes, custom exception shall be able to triggered with customize watcher.
it also shall be available to other standard watchers as well:

- @Controller
- @RestController
- @Service
- @Repository
- @Componen

The current Exception Assault fixes the Exception type as `java.lang.RuntimeException`, the key idea is to give flexibility in experiment to specify custom exception. 

Given an example, the application may failed to connect database indicated by `org.springframework.jdbc.CannotGetJdbcConnectionException`, and application will handle the exception by fallback to cache to retrieve the data. We may need to allow chaos monkey to raise the `org.springframework.jdbc.CannotGetJdbcConnectionException` to test the application resiliency in case of database unavailable.

**Comment by lipmanp** [comment]
The custom exception shall be child of RuntimeException

**Comment by MrBW** [comment]
https://github.com/codecentric/chaos-monkey-spring-boot/pull/59

**Comment by MrBW** [comment]
Available since 2.0.2 release of the Chaos Monkey for Spring Boot

**Comment by krupa814** [comment]
Hi. Custom exception injection is cool as far as my argument type is a string. I have a the scenario where I am trying to inject HttpClientErrorException to inject various httpstatus failure codes because httpStatus argument is an Enum. Any suggestions please help.

**Comment by maiksensi** [comment]
Hey @krupa814 thanks for reaching out via the issue tracker. 
I don't think what you're trying to do is currently supported. If you feel this is wrong, and is in fact a bug, please submit a minimal example to reproduce the issue. 
In any case, feel free to submit a MR or start a new issue to discuss your use case. 
Reaching out via stackoverflow is usually also a good idea, as more ppl tend to help there.

**Comment by WtfJoke** [comment]
This is not possible. The current logic instantiate parameters with Class.forName(), which doesnt work for enums. This would be enhancement, to pass Enums as Parameters on Exception-Assault. 

Code is [here](https://github.com/codecentric/chaos-monkey-spring-boot/blob/60586a0ab6848c7e9111150ff7ee8c2ffae700d9/chaos-monkey-spring-boot/src/main/java/de/codecentric/spring/boot/chaos/monkey/configuration/AssaultException.java#L58)
