### ISSUE TITLE
Supporting metrics features from v2.0.1 on v1.5.0.

### ISSUE THREAD

**Issue by yuyang-os** [codecentric/chaos-monkey-spring-boot#56]
Would the metric features on version 2.0.1 be replicated to version 1.5.0? Some applications are running on spring boot 1.5.0, and would take long to migrate to version 2.0 due to their complexity before they are able to use chaos-monkey-spring-boot. Would be great if you share your plans/thoughts on this.

**Comment by MrBW** [comment]
I like your idea and we should do this!

**Comment by maiksensi** [comment]
Closed by #68
