### ISSUE TITLE
Regarding the assaultlevel for applications spawning thread internally

### ISSUE THREAD

**Issue by abecedarius** [codecentric/chaos-monkey-spring-boot#58]
I have the boot application and which controller is calling the ervice it is spawning the async thread 
which in turn spawning the parallel threads with below configurations:

```
async.config.core.pool.size=20
async.config.max.pool.size=20
async.config.queue.capacity=20

parallel.call.config.core.pool.size=30
parallel.call.config.max.pool.size=30
parallel.call.config.queue.capacity=30
```
Now , when I am running the load on this application with the assault level as 10 , i am not getting the 10% failure rate.

Is there any calculation which will decide the failure rate for the application , say suppose if I put the assault level as 10 then should it not cause the 10% failure rate?

**Comment by MrBW** [comment]
Currently, a random value is determined, which should approximately reflect the level in percent. Until the last release, I didn't have any metrics that I could use as the basis for a calculation. But I would have to use a rolling window to count the requests. Only then could I determine more precisely how many requests are to be attacked in which time window.

If you have any ideas here, please share them with me. It's been a thorn in my side for quite some time and I'd like to improve it.

**Comment by F43nd1r** [comment]
From what I gathered this issue is about a mismatch between expected failure rate (assault level) and real failure rate. Is this correct?
 
If so, could this be fixed by providing an alternative mode to randomness? (Deterministic, e.g. attack every x requests)

Is this something we'd want to do?
