### ISSUE TITLE
Relaxed binding is not used in conditions

### ISSUE THREAD

**Issue by michalkarolik** [codecentric/chaos-monkey-spring-boot#61]
I've configured `chaos.monkey.watcher.rest-controller: true` ( intellij completed 'rest-controller' for me, so I may be not only one with this issue :) ) and it turned out that code inside `de.codecentric.spring.boot.chaos.monkey.conditions.AttackRestControllerCondition` does not fetch it - it returns false because `context.getEnvironment().getProperty("chaos.monkey.watcher.restController")` seems to not take relaxed binding into consideration.

I'm not sure if it's because core of spring does not use relaxed binding or it's some other issue.

**Comment by MrBW** [comment]
Hi, thx for this issue. I will take a look at it!
