### ISSUE TITLE
Use the project in Microservices packages as war

### ISSUE THREAD

**Issue by jabrena** [codecentric/chaos-monkey-spring-boot#69]
Hi,

In some scenarios, the Spring boot applications are packages as war files to be executed in one application server. For that scenarios, Does exist some way to use the project?

Many thanks in advance

Juan Antonio

**Comment by MrBW** [comment]
Hi,

it should work out of the box. I tested it some months ago and it works like charm.

Benjamin

**Comment by jabrena** [comment]
Many thanks, I will try it :)
