### ISSUE TITLE
unable to hit chaosmonkey endpoints

### ISSUE THREAD

**Issue by fergrea82** [codecentric/chaos-monkey-spring-boot#71]
I am using:
<dependency>
            <groupId>de.codecentric</groupId>
            <artifactId>chaos-monkey-spring-boot</artifactId>
            <version>1.5.0</version>
        </dependency>

I need to use this version as we are using springboot 1.5 in our application

Here is my basic config:
spring:
  profiles: chaos-monkey
chaos:
  monkey:
    enabled: true
    watcher:
      controller: false
      restController: false
      service: false
      repository: true
      component: false
    assaults:
      level: 3
      latencyActive: false
      exceptionsActive: true
      killApplicationActive: false
      latencyRangeStart: 3000
      latencyRangeEnd: 6000

When I hit any of the POST or GET chaosMonkey endpoints either from the browser or via curl i get 404 Not found in response

**Comment by sunnyaimx2** [comment]
did u get the answer for this, i am hitting the same issue.

**Comment by surajpanda1582** [comment]
Even I am facing same issue. I am using chaos monkey version 1.5 but endpoints are not getting exposed even after setting all the properties. Please let me know if anyone found solution to this.
