### ISSUE TITLE
Chaos Monkey is disabled and continue injecting Exceptions

### ISSUE THREAD

**Issue by bensonarce** [codecentric/chaos-monkey-spring-boot#78]
I have an app that use: 
Spring boot version: 2.1.3.RELEASE, 
Chaos Monkey: 2.0.0

 i want to understand how Chaos monkey works, when i disable "chaos" by endpoint at runtime, i continue calling some Rest Services, i can get some "chaos monkey" exceptions even some latency remains that, but latency disappear after some calls but exceptions continue for more time

thanks

**Comment by maiksensi** [comment]
@bensonarce Thanks for submitting an issue. That sounds "strange". Is there any chance you can provide a minimal working example to reproduce this?
Do you have specific questions on implementation details?

**Comment by maiksensi** [comment]
Closing this for now. If you are able to supply us with some more information, feel free to re-open this.
