### ISSUE TITLE
Same value for latencyRangeStart and latencyRangeEnd on LatencyAssault causes runtime error

### ISSUE THREAD

**Issue by kevin-peters** [codecentric/chaos-monkey-spring-boot#79]
Currently its not possible to set latencyRangeStart and latencyRangeEnd to the same value to force a fixed instead of a ranged delay.

Even worse, this becomes apparent during runtime:

`java.lang.IllegalArgumentException: bound must be greater than origin
        at java.util.concurrent.ThreadLocalRandom.nextInt(ThreadLocalRandom.java:378)
        at de.codecentric.spring.boot.chaos.monkey.assaults.LatencyAssault.attack(LatencyAssault.java:53)
`
A wrong configuration should be checked on property creation time (e.g. startup).
Using "workarounds" like setting 1000 and 1001 feels strange, so it should also be possible to set a fixed delay (same values).

Merge request incoming! ;)

**Comment by kevin-peters** [comment]
https://github.com/codecentric/chaos-monkey-spring-boot/pull/80

**Comment by maiksensi** [comment]
Closed by #80
