### ISSUE TITLE
Are response attacks supported?

### ISSUE THREAD

**Issue by dmurat** [codecentric/chaos-monkey-spring-boot#81]
I'm sorry if this is not an appropriate channel for questions, but I couldn't find another one.

I'm currently trying to comprehend chaos-monkey-spring-boot features and I noticed only attacks for requests. Are response attacks supported? It looks like, for example, that latency attack could be handy for responses too since it can simulate correct execution of business logic (including transactions) results of which arrive at the client with delay or not at all. 

Tnx

**Comment by MrBW** [comment]
Hello,

the Chaos Monkey reacts to the call of a public method and executes the attack directly. Up to now it is not possible to trigger this behaviour when leaving the method.

But it would be a nice extension, which is also technically possible. ;-)

**Comment by maiksensi** [comment]
As @MrBW stated, it seems like a nice extension. @dmurat if you'd like to work on a feature merge request regarding this let us know and re-open this. I am closing this as answered.
