### ISSUE TITLE
memoryAssault

### ISSUE THREAD

**Issue by LucasHolzmann** [codecentric/chaos-monkey-spring-boot#83]
Hi,
I saw in your source code that there was a memoryAssault function. I managed to use it, but don't really understand how it works, especially how the memoryFillIncrementFraction and memoryFillTargetFraction parameters are used. Is there any documentation ? Or could you give me a brief explanation on it ?

**Comment by maiksensi** [comment]
@LucasHolzmann as I understand the options they would do the following: 
- `memoryFillIncrementFraction`: Increment memory fill by defined fraction; what is the rate you want your memory to fill.
- `memoryFillTargetFraction`: Target fraction of available memory; what is the desired amount of memory you want to fill up.

@MrBW please let me know if that is correct. I could add that to the docs if it's missing.

**Comment by maiksensi** [comment]
added #89

**Comment by maiksensi** [comment]
Closing this for now. The memory assault will be part of the next release and the docs are added. Feel free to open this again if things are still unclear.
