### ISSUE TITLE
Fix ChaosDemoApplicationTests#checkMetricsBean

### ISSUE THREAD

**Issue by WtfJoke** [codecentric/chaos-monkey-spring-boot#90]
The test (in demo project ext-jar) fails under windows and should be fixed

**Comment by WtfJoke** [comment]
It fails also on linux when executed directly in IDE (intellij)

**Comment by F43nd1r** [comment]
I don't think there is anything to fix here. This is by design. The ext-jar isn't available if it isn't added externally (e.g. in the IDE test run config).

I'm not sure if this can be tested in a way which doesn't require external configuration. I'd remove the test.

**Comment by WtfJoke** [comment]
> I don't think there is anything to fix here. This is by design. The ext-jar isn't available if it isn't added externally (e.g. in the IDE test run config).
> 
> I'm not sure if this can be tested in a way which doesn't require external configuration. I'd remove the test.

Lets remove it 🔥

**Comment by WtfJoke** [comment]
Fixed/removed with #262
